# Generated by Django 5.2.13 on 2026-09-18 15:06

# Django
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveEntity",
            fields=[
                (
                    "eve_id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[(3, "station"), (65, "structure"), (0, "(unknown)")],
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "alliance",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alli",
                        to="aafenrir.eveentity",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corp",
                        to="aafenrir.eveentity",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="Eve Online location ID, either item ID for stations or structure ID for structures",
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.PositiveIntegerField(
                        choices=[(3, "station"), (65, "structure"), (0, "(unknown)")],
                        default=0,
                        help_text="Eve Online category ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="In-game name of this station or structure",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "solar_system_id",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Eve Online solar system ID",
                        null=True,
                    ),
                ),
                (
                    "type_id",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Eve Online type ID",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.IntegerField(verbose_name="Contract ID")),
                ("collateral", models.FloatField(verbose_name="Collateral")),
                (
                    "date_accepted",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Date Accepted",
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Date Completed",
                    ),
                ),
                ("date_expired", models.DateTimeField(verbose_name="Date Expired")),
                ("date_issued", models.DateTimeField(verbose_name="Date Issued")),
                (
                    "date_notified",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Datetime of latest notification, None = none has been sent",
                        null=True,
                        verbose_name="Date Notified",
                    ),
                ),
                (
                    "days_to_complete",
                    models.IntegerField(verbose_name="Days to Complete"),
                ),
                (
                    "for_corporation",
                    models.BooleanField(verbose_name="For Corporation"),
                ),
                ("reward", models.FloatField(verbose_name="Reward")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("finished_issuer", "Finished Issuer"),
                            ("finished_contractor", "Finished Contractor"),
                            ("finished", "Finished"),
                            ("canceled", "Canceled"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                ("volume", models.FloatField(verbose_name="Volume")),
                (
                    "acceptor",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Character of acceptor or None if accepted by corp",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts_acceptor",
                        to="eveonline.evecharacter",
                        verbose_name="Acceptor",
                    ),
                ),
                (
                    "acceptor_corporation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Corporation of acceptor",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts_acceptor_corporation",
                        to="eveonline.evecorporationinfo",
                        verbose_name="Acceptor Corporation",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts_issuer",
                        to="eveonline.evecharacter",
                        verbose_name="Issuer",
                    ),
                ),
                (
                    "issuer_corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts_issuer_corporation",
                        to="eveonline.evecorporationinfo",
                        verbose_name="Issuer Corporation",
                    ),
                ),
                (
                    "end_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts_end_location",
                        to="aafenrir.location",
                        verbose_name="End Location",
                    ),
                ),
                (
                    "start_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts_start_location",
                        to="aafenrir.location",
                        verbose_name="Start Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disable_notifications", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ContractCustomerNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("finished_issuer", "Finished Issuer"),
                            ("finished_contractor", "Finished Contractor"),
                            ("finished", "Finished"),
                            ("canceled", "Canceled"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "date_notified",
                    models.DateTimeField(
                        help_text="datetime of notification",
                        verbose_name="Date Notified",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aafenrir_notifications",
                        to="aafenrir.contract",
                        verbose_name="Contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract customer notification",
                "default_permissions": (),
                "unique_together": {("contract", "status")},
            },
        ),
        migrations.CreateModel(
            name="ContractHandler",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="aafenrir.eveentity",
                        verbose_name="organization",
                    ),
                ),
                (
                    "version_hash",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="hash to identify changes to contracts",
                        max_length=32,
                        null=True,
                        verbose_name="version hash",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="when the last sync happened",
                        null=True,
                        verbose_name="last sync at",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        default=None,
                        help_text="Character used for syncing contracts",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="authentication.characterownership",
                        verbose_name="Character",
                    ),
                ),
            ],
            options={
                "verbose_name": "contract handler",
                "verbose_name_plural": "contract handler",
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="handler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aafenrir_contracts",
                to="aafenrir.contracthandler",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["status"], name="aafenrir_co_status_fe1ea6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("handler", "contract_id")},
        ),
    ]
