# Generated by Django 5.2.13 on 2026-09-20 05:03

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aafenrir", "0001_initial"),
        ("eve_sde", "0036_remove_star_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="quick_select_presets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="RoutePreset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "origin_system_station",
                    models.CharField(
                        blank=True, default="N/A", max_length=100, null=True
                    ),
                ),
                (
                    "destination_system_station",
                    models.CharField(
                        blank=True, default="N/A", max_length=100, null=True
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("jumpfreighter", "Jumpfreighter"),
                            ("deep_space_transport", "Deep Space Transport"),
                            ("freighter", "Freighter"),
                        ],
                        default="N/A",
                        help_text="Type of service for the route",
                        max_length=100,
                    ),
                ),
                (
                    "max_volume",
                    models.IntegerField(
                        default=0, help_text="Maximum volume for the route"
                    ),
                ),
                (
                    "max_collateral",
                    models.BigIntegerField(
                        default=0, help_text="Maximum collateral for the route"
                    ),
                ),
                (
                    "base_fee",
                    models.IntegerField(
                        default=5000000, help_text="Base fee for the route"
                    ),
                ),
                (
                    "fee_per_m3",
                    models.IntegerField(
                        default=0, help_text="Fee per cubic meter for the route"
                    ),
                ),
                (
                    "fee_per_ly",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Fee per light-year for the route",
                        max_digits=20,
                    ),
                ),
                (
                    "collateral_percent",
                    models.IntegerField(
                        default=0, help_text="Collateral percentage for the route"
                    ),
                ),
                (
                    "min_reward",
                    models.IntegerField(
                        default=0, help_text="Minimum reward for the route"
                    ),
                ),
                (
                    "estimated_time",
                    models.IntegerField(
                        default=0, help_text="Estimated time for the route in minutes"
                    ),
                ),
                (
                    "is_cyno_route",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the route is a cyno route",
                    ),
                ),
                (
                    "danger_level",
                    models.CharField(
                        choices=[("safe", "Safe"), ("cyno_guarded", "Cyno Guarded")],
                        default="N/A",
                        help_text="Danger level for the route",
                        max_length=100,
                    ),
                ),
                (
                    "cyno_waypoints",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cyno waypoints for the route",
                        related_name="+",
                        to="eve_sde.solarsystem",
                    ),
                ),
                (
                    "destination_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.solarsystem",
                    ),
                ),
                (
                    "origin_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
