# Generated by Django 5.2.13 on 2026-09-20 07:59

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aafenrir", "0002_usersettings_quick_select_presets_routepreset"),
        ("eve_sde", "0036_remove_star_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteSystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
