# Generated by Django 5.2.13 on 2026-09-20 14:04

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aafenrir", "0003_routesystem"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AA-Fenrir",
                "verbose_name_plural": "AA-Fenrir",
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("manage_access", "Can manage"),
                    ("full_access", "Full access"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
