# Generated by Django 5.2.13 on 2026-09-20 19:34

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aafenrir", "0004_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="routepreset",
            name="has_alliance_subsidy",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if alliance subsidy is enabled for this route",
            ),
        ),
    ]
