# Generated by Django 5.2.13 on 2026-09-20 19:50

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aafenrir", "0005_routepreset_has_alliance_subsidy"),
    ]

    operations = [
        migrations.AddField(
            model_name="routepreset",
            name="assign_corp",
            field=models.ForeignKey(
                blank=True,
                help_text="Contract handler corporation/alliance to assign contracts to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="aafenrir.contracthandler",
            ),
        ),
        migrations.AddField(
            model_name="routepreset",
            name="expiration_days",
            field=models.IntegerField(
                default=7, help_text="Days until courier contract expires"
            ),
        ),
        migrations.AddField(
            model_name="routepreset",
            name="days_to_complete",
            field=models.IntegerField(
                default=3, help_text="Days to complete the contract"
            ),
        ),
    ]
