# Generated by Django 5.2.13 on 2026-09-21 19:47

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aafenrir", "0006_routepreset_contract_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routepreset",
            name="collateral_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Collateral percentage for the route",
                max_digits=5,
            ),
        ),
    ]
