/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/aafenrir/api/menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Menu */
        get: operations["aafenrir_api_general_get_menu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["aafenrir_api_general_get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/modify/user/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Modify User Settings */
        post: operations["aafenrir_api_general_modify_user_settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/contract/presets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route Presets */
        get: operations["aafenrir_api_contract_get_route_presets"];
        put?: never;
        /** Create Route Preset */
        post: operations["aafenrir_api_contract_create_route_preset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/contract/preset/{preset_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route Preset */
        get: operations["aafenrir_api_contract_get_route_preset"];
        /** Update Route Preset */
        put: operations["aafenrir_api_contract_update_route_preset"];
        post?: never;
        /** Delete Route Preset */
        delete: operations["aafenrir_api_contract_delete_route_preset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/contract/{contract_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["aafenrir_api_contract_get_contract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/contract/queue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract Queue */
        get: operations["aafenrir_api_contract_get_contract_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/contract/systems/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route Systems */
        get: operations["aafenrir_api_contract_get_route_systems"];
        put?: never;
        /** Add Route System */
        post: operations["aafenrir_api_contract_add_route_system"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/contract/system/{system_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Route System */
        delete: operations["aafenrir_api_contract_delete_route_system"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/eve_sde/solar-systems/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Solar Systems */
        get: operations["aafenrir_api_eve_sde_search_solar_systems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aafenrir/api/eve_sde/solar-system/{eve_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Solar System */
        get: operations["aafenrir_api_eve_sde_get_solar_system"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * MenuLink
         * @description Represents a link in the menu.
         *
         *     Parameters:
         *         name (str): The name of the menu link.
         *         link (str | None): The URL or path the menu link points to.
         */
        MenuLink: {
            /** Name */
            name: string;
            /** Link */
            link?: string;
            /**
             * Is External
             * @default false
             */
            is_external?: boolean;
        };
        /**
         * MenuModalSchema
         * @description Schema for menu modals
         */
        MenuModalSchema: {
            create_aafenrir?: components["schemas"]["ModalSchema"] | null;
        };
        /**
         * MenuSchema
         * @description Schema for the overall menu, including links and modals.
         *
         *     Parameters:
         *         links (list[MenuLink]): The list of links in the menu.
         *         modals (MenuModalSchema | None): The modals associated with the menu.
         */
        MenuSchema: {
            /**
             * Left Links
             * @default []
             */
            left_links: components["schemas"]["MenuLink"][];
            /**
             * Right Links
             * @default []
             */
            right_links: components["schemas"]["MenuLink"][];
            modals?: components["schemas"]["MenuModalSchema"] | null;
        };
        /**
         * ModalSchema
         * @description Schema for modal dialog data.
         */
        ModalSchema: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Icon */
            icon: string;
            /** Modal Id */
            modal_id: string;
            /** Url */
            url: string;
            /** Color */
            color?: string | null;
            /** Buttontext */
            buttonText?: string | null;
        };
        /**
         * UserData
         * @description Schema for user data, including character ID and character name.
         *
         *     Parameters:
         *         user_id (int): The ID of the user.
         *         character_id (int): The ID of the character associated with the user.
         *         character_name (str): The name of the character.
         *         portrait (str | None): The URL or path to the character's portrait image.
         *         notification (boolean): The notification status for the user.
         */
        UserData: {
            /** User Id */
            user_id: number;
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Portrait */
            portrait?: string | null;
            /** Notification */
            notification: boolean;
            /**
             * Quick Select Presets
             * @default []
             */
            quick_select_presets: number[];
            /**
             * Has Manage Access
             * @default false
             */
            has_manage_access: boolean;
        };
        /**
         * RoutePresetSchema
         * @description Schema for RoutePreset.
         */
        RoutePresetSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Origin System */
            origin_system: string;
            /** Origin System Id */
            origin_system_id?: number | null;
            /**
             * Origin Station
             * @default
             */
            origin_station: string;
            /** Destination System */
            destination_system: string;
            /** Destination System Id */
            destination_system_id?: number | null;
            /**
             * Destination Station
             * @default
             */
            destination_station: string;
            /** Service Type */
            service_type: string;
            /** Max Volume */
            max_volume: number;
            /** Max Collateral */
            max_collateral: number;
            /** Base Fee */
            base_fee: number;
            /** Fee Per M3 */
            fee_per_m3: number;
            /** Fee Per Ly */
            fee_per_ly: number;
            /**
             * Fee Per Ly Or Jump
             * @default 0
             */
            fee_per_ly_or_jump: number;
            /**
             * Fee Per Lyorjump
             * @default 0
             */
            fee_per_lyorjump: number;
            /** Collateral Percent */
            collateral_percent: number;
            /** Min Reward */
            min_reward: number;
            /** Estimated Time */
            estimated_time: number;
            /** Estimated Days */
            estimated_days: number;
            /** Is Cyno Route */
            is_cyno_route: boolean;
            /**
             * Cyno Waypoints
             * @default []
             */
            cyno_waypoints: string[];
            /**
             * Cyno Waypoint Ids
             * @default []
             */
            cyno_waypoint_ids: number[];
            /** Danger Level */
            danger_level: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * CreateRoutePresetSchema
         * @description Schema for creating a RoutePreset.
         */
        CreateRoutePresetSchema: {
            /** Name */
            name: string;
            /** Origin System Id */
            origin_system_id: number;
            /**
             * Origin System Station
             * @default
             */
            origin_system_station: string;
            /** Destination System Id */
            destination_system_id: number;
            /**
             * Destination System Station
             * @default
             */
            destination_system_station: string;
            /**
             * Service Type
             * @default jumpfreighter
             */
            service_type: string;
            /**
             * Max Volume
             * @default 0
             */
            max_volume: number;
            /**
             * Max Collateral
             * @default 0
             */
            max_collateral: number;
            /**
             * Base Fee
             * @default 5000000
             */
            base_fee: number;
            /**
             * Fee Per M3
             * @default 0
             */
            fee_per_m3: number;
            /**
             * Fee Per Ly
             * @default 0
             */
            fee_per_ly: number;
            /**
             * Collateral Percent
             * @default 0
             */
            collateral_percent: number;
            /**
             * Min Reward
             * @default 0
             */
            min_reward: number;
            /**
             * Estimated Time
             * @default 0
             */
            estimated_time: number;
            /**
             * Is Cyno Route
             * @default false
             */
            is_cyno_route: boolean;
            /**
             * Cyno Waypoint Ids
             * @default []
             */
            cyno_waypoint_ids: number[];
            /**
             * Danger Level
             * @default safe
             */
            danger_level: string;
        };
        /**
         * SolarSystemSchema
         * @description Schema for a solar system entry.
         */
        SolarSystemSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Border */
            border: boolean;
            /** Constellation Id */
            constellation_id: number;
            /** Corridor */
            corridor: boolean;
            /** Faction Id Raw */
            faction_id_raw: number;
            /** Fringe */
            fringe: boolean;
            /** Hub */
            hub: boolean;
            /** International */
            international: boolean;
            /** Luminosity */
            luminosity: number;
            /** Radius */
            radius: number;
            /** Regional */
            regional: boolean;
            /** Security Class */
            security_class: string;
            /** Security Status */
            security_status: number;
            /** Visual Effect */
            visual_effect: string;
            /** Wormhole Class Id Raw */
            wormhole_class_id_raw: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** X 2D */
            x_2d: number;
            /** Y 2D */
            y_2d: number;
        };
        /**
         * ContractSchema
         * @description Schema for courier contract queue data.
         */
        ContractSchema: {
            id: number;
            contract_id: number;
            title?: string | null;
            status: string;
            status_display: string;
            issuer_name: string;
            issuer_corporation_name?: string;
            issuer_corporation_ticker?: string;
            start_location_name: string;
            start_location_solar_system: string;
            end_location_name: string;
            end_location_solar_system: string;
            volume: number;
            collateral: number;
            reward: number;
            date_issued: string;
            date_expired: string;
            date_accepted?: string | null;
            date_completed?: string | null;
            days_to_complete: number;
            acceptor_name?: string | null;
            for_corporation: boolean;
        };
        /**
         * RouteSystemSchema
         * @description Schema for an available route solar system.
         */
        RouteSystemSchema: {
            id: number;
            system_id: number;
            name: string;
            security_status: number;
            security_class: string;
            region_name?: string;
            x?: number;
            y?: number;
            z?: number;
        };
        /**
         * AddRouteSystemSchema
         * @description Schema for adding a solar system to available route systems.
         */
        AddRouteSystemSchema: {
            system_id: number;
        };
        /**
         * SolarSystemSearchSchema
         * @description Schema for solar system search results.
         */
        SolarSystemSearchSchema: {
            id: number;
            name: string;
            security_status: number;
            security_class: string;
            region_name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    aafenrir_api_general_get_menu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuSchema"];
                };
            };
        };
    };
    aafenrir_api_general_get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_general_modify_user_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_get_route_presets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePresetSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_create_route_preset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoutePresetSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePresetSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_get_route_preset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePresetSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_update_route_preset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoutePresetSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePresetSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_delete_route_preset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_get_contract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuSchema"];
                };
            };
        };
    };
    aafenrir_api_eve_sde_get_solar_system: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eve_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolarSystemSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_get_contract_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_get_route_systems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSystemSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_add_route_system: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRouteSystemSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSystemSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_contract_delete_route_system: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    aafenrir_api_eve_sde_search_solar_systems: {
        parameters: {
            query?: {
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolarSystemSearchSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
